### ISSUE TITLE
Can't access to install

### ISSUE THREAD

**Issue by pand-app** [WebTales/rubedo#572]
Hello,

After an installation without problems on local sandbox (Linux Mint Olivia), I try an installation on prod openVZ with PHP and mongoDB connector. MongoDB and elasticSearch are on differents openVZ.
In this situation, with version 1.3 and 1.4 I have no problem.
All openVZ are on debian 7.0.2.

Here, when I try to access to {url}/install, He try to connect to localhost mongoDB database. He can't do that and he return this fatal error (below).
On current branch and next branch.

```
[Thu Oct 24 21:42:02 2013] [error] [client {ip}] PHP Fatal error:  Uncaught exception 'MongoConnectionException' with message 'Failed to connect to: localhost:27017: Connection refused' in {path}/module/Rubedo/src/Rubedo/Mongo/DataAccess.php:248
Stack trace:
#0 {path}/module/Rubedo/src/Rubedo/Mongo/DataAccess.php(248): MongoClient->__construct('mongodb://local...')
#1 {path}/module/Rubedo/Module.php(348): Rubedo\\Mongo\\DataAccess->getAdapter('mongodb://local...')
#2 {path}/module/Rubedo/Module.php(60): Rubedo\\Module->initializeSession(Object(Zend\\Mvc\\MvcEvent))
#3 [internal function]: Rubedo\\Module->onBootstrap(Object(Zend\\Mvc\\MvcEvent))
#4 {path}/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\\Mvc\\MvcEvent))
#5 {path}/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\\EventManager\\EventManager->triggerListeners('bootstrap', Object(Zend\\Mvc\\MvcEvent), Array)
#6 /h in {path}/module/Rubedo/src/Rubedo/Mongo/DataAccess.php on line 248
```

If I try to edit with vi cache/config/module-config-cache..php (because I have no idea for the correct syntax of config file local.php, too different with 1.4) and search and replace mongoDB informations, he try to connect to 'admin' database which no exist.

```
[Thu Oct 24 22:42:40 2013] [error] [client {ip}] PHP Fatal error:  Uncaught exception 'MongoConnectionException' with message 'Failed to connect to: {mongoDBIp}:27017: Authentication failed on database 'admin' with username '{correctUsername}': auth fails' in {path}/module/Rubedo/src/Rubedo/Mongo/DataAccess.php:248
Stack trace:
#0 {path}/module/Rubedo/src/Rubedo/Mongo/DataAccess.php(248): MongoClient->__construct('mongodb://rubed...')
#1 {path}/module/Rubedo/Module.php(348): Rubedo\\Mongo\\DataAccess->getAdapter('mongodb://rubed...')
#2 {path}/module/Rubedo/Module.php(60): Rubedo\\Module->initializeSession(Object(Zend\\Mvc\\MvcEvent))
#3 [internal function]: Rubedo\\Module->onBootstrap(Object(Zend\\Mvc\\MvcEvent))
#4 {path}/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\\Mvc\\MvcEvent))
#5 {path}/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\\EventManager\\EventManager->tri in /home/php/rubedoPrunding/module/Rubedo/src/Rubedo/Mongo/DataAccess.php on line 248
```

I don't understand this behavior...
I think about a extend in global config but I don't found 'admin' database.

Have a nice day,
Gaël

**Comment by pand-app** [comment]
If I add my user to "admin" database, It's work. Why ?

**Comment by jbourdin** [comment]
Is there remaining cases for such a problem ?

**Comment by pand-app** [comment]
Yes, same case on Debian VM (but not on my linux mint), mongo 2.4. When I add the user and password for db, next step fail (next branch). If User not exist on db "admin", the try/catch return an error and can't create session.
